steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubesec:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${BRANCH_NAME}" == "master" ]]; then docker push gcr.io/${PROJECT_ID}/kubesec:${SHORT_SHA}; fi
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${BRANCH_NAME}" == "master" ]]; then gcloud beta run deploy kubesec --image gcr.io/${PROJECT_ID}/kubesec:${SHORT_SHA} --region us-central1; fi
